sudo: false
language: python
jdk:
  - oraclejdk7
before_install:
  # install Neo4j locally:
  - wget http://dist.neo4j.org/neo4j-community-2.3.10-unix.tar.gz
  - tar -xzf neo4j-community-2.3.10-unix.tar.gz
  - ./neo4j-community-2.3.10/bin/neo4j start
python:
  - "2.7"
  - "pypy"
install:
  - pip install flask
  - pip install flask_classful
  - python setup.py -q install
script: py.test